### PR TITLE
Assertj update

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by aaschmid** [comment]
thx @PascalSchumacher, do you use junit-dataprovider?

**Comment by PascalSchumacher** [comment]
Yes we use it in assertj and I use it at work.

**Comment by aaschmid** [comment]
Oh great to hear. 
If you need any features, just let me know. I am always open minded (even if JUnit and/or Java sometimes are to inflexible :-( )

**Comment by PascalSchumacher** [comment]
Thanks. If I need anything I will open an issue. :smile: 

There has been some progress with recent java versions and I have great expectations for https://github.com/junit-team/junit5

Since I started to use assertj and junit-dataprovider with junit i do not miss using spock that much.

**Comment by janschaefer** [comment]
If you miss the BDD part of Spock, you could try [JGiven](http://jgiven.org) :-)

**Comment by aaschmid** [comment]
Hehe, I know about junit-lamba and really looking forward to it. I know one of the guys in the team having the some troubles extending junit for his https://github.com/bechte/junit-hierarchicalcontextrunner ...

**Pull request merged**
