### PR TITLE
added crossproduct of data providers

### PR DESCRIPTION
**Pull request by ritschwumm**
take it or leave it - i found it quite useful to have a crossproduct

### CODE REVIEW

**Comment by aaschmid** [comment]
Hi @ritschwumm, 

thanks for your pull request. Can you add some testcases for your function? After getting some test cases I would like to approve and merge your pull request.

Cheers,
Andreas

**Comment by ritschwumm** [comment]
maybe - i don't actually use junit-dataprovider any more, but had the code still lying around for a year and thought someone might find it useful.

**Comment by aaschmid** [comment]
Ok, so any other improvements you would like to have to use it again ;-)

**Comment by ritschwumm** [comment]
ok, added some tests.

about other improvements: how about type-safety?
not being serious, but reading a type like ```Object[][]```
makes me shiver.

**Comment by aaschmid** [comment]
Thanks for the test cases, I will have a more detailed look soon.

Type safety, yes. Like that and would be happy getting it. Have you any ideas? (however it's test cases and not production code. Therefore it might not that important but still would be a very useful improvement). I have a lot but no good ones. Would also like to get the String naming the dataprovider method to use, checked by the compiler. Would be possible using some annotation preprocessing but have no other ideas ...

**Comment by ritschwumm** [comment]
not really - this is java, after all :/

**Comment by aaschmid** [comment]
Thanks for this PR

**Comment by aaschmid** [comment]
Hi @ritschwumm, 

I know that your PR request is a some time ago. Can you hereby agree to the new CLA:

> * You will only submit contributions where you have authored 100% of the content.
> * You will only submit contributions to which you have the necessary rights. This means in particular, that if you are employed you have received the necessary permissions from your employer to make the contributions.
> * Whatever content you contribute will be provided under the project license(s) (see "LICENSE.txt")

Thank you very much again for your PR :-)

**Pull request merged**
